// =============================================================================
// MODULE: camera
// AUTO-GENERATED from src/gpu_types.nim (CameraLayout) - DO NOT EDIT
// Regenerated by tools/wgsl_bundle.nim on every build.
// =============================================================================

struct Camera {
  centerX: f32,
  centerY: f32,
  zoom: f32,
  pad0: f32,
}
