// =============================================================================
// MODULE: overlay_params
// AUTO-GENERATED from src/gpu_types.nim (OverlayParamsLayout) - DO NOT EDIT
// Regenerated by tools/wgsl_bundle.nim on every build.
// =============================================================================

struct OverlayParams {
  kind: f32,
  centerX: f32,
  centerY: f32,
  radius: f32,
}
