// =============================================================================
// MODULE: reaction_params
// AUTO-GENERATED from src/gpu_types.nim (ReactionParamsLayout) - DO NOT EDIT
// Regenerated by tools/wgsl_bundle.nim on every build.
// =============================================================================

struct ReactionParams {
  reactionKind: f32,
  kernelRadius: f32,
  growthMu: f32,
  growthSigma: f32,
  growthDt: f32,
  pad0: f32,
  pad1: f32,
  pad2: f32,
}
