// =============================================================================
// MODULE: species_chemistry
// AUTO-GENERATED from src/gpu_types.nim (SpeciesChemistryLayout) - DO NOT EDIT
// Regenerated by tools/wgsl_bundle.nim on every build.
// =============================================================================

struct SpeciesChemistry {
  secretion: array<vec4<f32>, 2>,
  tropism: array<vec4<f32>, 2>,
}
