// =============================================================================
// AUTO-GENERATED BY tools/wgsl_bundle.nim - DO NOT EDIT DIRECTLY
// =============================================================================
// Source: web/shaders/src/bin-count.wgsl
// Bundled modules: grid_params, cell_index, particle
// Generated: 2026-07-19T21:52:36+02:00
// =============================================================================

// ─────────────────────────────────────────────────────────────────────────────
// MODULE: grid_params
// Source: web/shaders/modules/grid_params.wgsl
// ─────────────────────────────────────────────────────────────────────────────

// =============================================================================
// MODULE: grid_params
// =============================================================================
// GridParams uniform struct for spatial hashing passes.
//
// Used by: bin-count, bin-scatter
//
// ALIGNMENT: 32 bytes (padded to 16-byte boundary for uniform buffer)
// =============================================================================

struct GridParams {
  gridW: u32,           // Grid width in cells
  gridH: u32,           // Grid height in cells
  canvasWidth: f32,     // World width in pixels
  canvasHeight: f32,    // World height in pixels
  particleCount: u32,   // Number of active particles
  padding0: u32,        // Align to 16 bytes
  padding1: u32,
  padding2: u32,
}

// ─────────────────────────────────────────────────────────────────────────────
// MODULE: cell_index
// Source: web/shaders/modules/cell_index.wgsl
// ─────────────────────────────────────────────────────────────────────────────

// =============================================================================
// MODULE: cell_index
// =============================================================================
// Cell index computation for spatial hashing.
//
// Used by: bin-count, bin-scatter (and potentially forces for toroidal wrapping)
//
// ALGORITHM:
// 1. Divide world space by grid dimensions to get cell size
// 2. Floor particle position to cell coordinates
// 3. Clamp to grid bounds (handles out-of-bounds particles)
// 4. Compute linear index: cellY * gridW + cellX
// =============================================================================


// Compute linear cell index from particle position
fn computeCellIndex(pos: vec2<f32>, params: GridParams) -> u32 {
  // Inverse cell dimensions (world-to-cell transform)
  let invCellW = f32(params.gridW) / params.canvasWidth;
  let invCellH = f32(params.gridH) / params.canvasHeight;

  // Compute cell coordinates
  var cx = u32(pos.x * invCellW);
  var cy = u32(pos.y * invCellH);

  // Clamp to grid bounds (handles edge cases)
  if (cx >= params.gridW) {
    cx = params.gridW - 1u;
  }
  if (cy >= params.gridH) {
    cy = params.gridH - 1u;
  }

  // Linear index (row-major order)
  return cy * params.gridW + cx;
}

// ─────────────────────────────────────────────────────────────────────────────
// MODULE: particle
// Source: web/shaders/modules/particle.wgsl
// ─────────────────────────────────────────────────────────────────────────────

// =============================================================================
// MODULE: particle
// =============================================================================
// Particle struct: 32 bytes, cache-aligned AoS layout.
//
// Source of truth: src/memory_layout.nim
// This definition MUST match the Nim memory layout exactly.
//
// CACHE BEHAVIOR:
// - Two particles fit in one 64-byte CPU cache line
// - Four particles fit in one 128-byte GPU cache line
// - 32-byte alignment avoids straddling cache line boundaries
//
// FIELD LAYOUT:
// ┌─────────┬──────────┬───────┬─────────────────────────────────────────────┐
// │ Offset  │ Field    │ Size  │ Description                                 │
// ├─────────┼──────────┼───────┼─────────────────────────────────────────────┤
// │ 0       │ pos      │ 8     │ Position (vec2<f32>)                        │
// │ 8       │ vel      │ 8     │ Velocity (vec2<f32>)                        │
// │ 16      │ species  │ 4     │ Species ID (u32, 0-5)                       │
// │ 20      │ density  │ 4     │ Local density (f32)                         │
// │ 24      │ _pad0    │ 4     │ Padding for 32-byte alignment               │
// │ 28      │ _pad1    │ 4     │ Padding for 32-byte alignment               │
// └─────────┴──────────┴───────┴─────────────────────────────────────────────┘
// =============================================================================

struct Particle {
  pos: vec2<f32>,    // offset 0, size 8
  vel: vec2<f32>,    // offset 8, size 8
  species: u32,      // offset 16, size 4
  density: f32,      // offset 20, size 4
  _pad0: u32,        // offset 24, size 4
  _pad1: u32,        // offset 28, size 4
}

// Maximum species count - MUST match memory_layout.nim:MAX_SPECIES
const MAX_SPECIES: u32 = 6u;

// ─────────────────────────────────────────────────────────────────────────────
// MAIN SHADER
// ─────────────────────────────────────────────────────────────────────────────

// =============================================================================
// BIN-COUNT: Count particles per cell using atomic increments (Pass 1)
// =============================================================================
//
// WHY THIS EXISTS:
// First pass of spatial hashing - counts how many particles fall into each grid
// cell. These counts feed into prefix sum to compute cell offsets for scattering.
//
// ALGORITHM:
// 1. Each thread processes one particle
// 2. Read particle position from AoS buffer
// 3. Compute cell index from position and grid dimensions
// 4. Clamp to grid bounds (handles edge cases)
// 5. Atomically increment cellCounts[cellIdx]
//
// BINDING MANIFEST:
// +-------+---------------------------+-----------------+--------+
// | Bind  | Shader Type               | JS Buffer       | Access |
// +-------+---------------------------+-----------------+--------+
// |   0   | uniform GridParams        | gridParams      | read   |
// |   1   | storage array<Particle>   | particles       | read   |
// |   2   | storage array<atomic<u32>>| cellCounts      | r/w    |
// +-------+---------------------------+-----------------+--------+
//
// THREAD MAPPING: One thread per particle (global_invocation_id.x = particleIdx)
// =============================================================================


@group(0) @binding(0) var<uniform> params: GridParams;
@group(0) @binding(1) var<storage, read> particles: array<Particle>;
@group(0) @binding(2) var<storage, read_write> cellCounts: array<atomic<u32>>;

@compute @workgroup_size(128)
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {
  let particleIdx = global_id.x;

  // Bounds check - return early if beyond particle count
  if (particleIdx >= params.particleCount) {
    return;
  }

  // Read particle position from AoS buffer
  let p = particles[particleIdx];

  // Compute cell index using shared function
  let cellIdx = computeCellIndex(p.pos, params);

  // Atomic increment - this is the core counting operation
  atomicAdd(&cellCounts[cellIdx], 1u);
}
