# This tool preprocesses WGSL shaders by:
# 1. Resolving //! import directives (module system)
# 2. Substituting {{PLACEHOLDER}} values from shader_config.nim
# 3. Generating WGSL struct modules from gpu_types.nim's layout tables.
#
# USAGE:
#   nim c -r --path:src tools/wgsl_bundle.nim (or: just shaders)
#
# The bundler reads from web/shaders/src/*.wgsl, resolves imports from
# web/shaders/modules/, and writes bundled output to web/shaders/*.wgsl.
#
# IMPORT SYNTAX:
#   //! import particle
#   //! import cell_index
#
# This directive must appear at the start of a line. The module name maps to
# web/shaders/modules/{name}.wgsl. Imports are topologically sorted and
# deduplicated.

import std/[os, strutils, tables, sets, times, hashes]
import shader_config
import gpu_types
import wgsl_lint
import memory_layout

const
  ModulesDir = "web/shaders/modules"
  SrcDir = "web/shaders/src"
  OutDir = "web/shaders"

type
  Module = object
    name: string
    path: string
    content: string
    imports: seq[string]

proc parseImports(content: string): seq[string] =
  ## Extract module names from //! import directives.
  ## Returns deduplicated list in declaration order.
  var seen: HashSet[string]
  for line in content.splitLines:
    let trimmed = line.strip
    if trimmed.startsWith("//! import "):
      let moduleName = trimmed[11..^1].strip
      if moduleName notin seen:
        seen.incl(moduleName)
        result.add(moduleName)

proc stripImportDirectives(content: string): string =
  var lines: seq[string]
  for line in content.splitLines:
    if not line.strip.startsWith("//! import"):
      lines.add(line)
  result = lines.join("\n")

proc loadModule(name: string, loaded: var Table[string, Module]): Module =
  ## Load a module by name, caching in `loaded` table.
  if name in loaded:
    return loaded[name]

  let path = ModulesDir / name & ".wgsl"
  if not fileExists(path):
    quit "Error: Module not found: " & path

  result.name = name
  result.path = path
  result.content = readFile(path)
  result.imports = parseImports(result.content)
  loaded[name] = result

proc topologicalSort(modules: Table[string, Module]): seq[string] =
  ## Kahn's algorithm for dependency ordering.
  ## Returns module names in order such that dependencies come before dependents.
  var inDegree: Table[string, int]
  var graph: Table[string, seq[string]]  # dependency -> dependents

  for name in modules.keys:
    if name notin inDegree:
      inDegree[name] = 0

  for name, m in modules:
    for dep in m.imports:
      if dep notin graph:
        graph[dep] = @[]
      graph[dep].add(name)
      inDegree[name] = inDegree.getOrDefault(name, 0) + 1

  var queue: seq[string]
  for name, deg in inDegree:
    if deg == 0:
      queue.add(name)

  while queue.len > 0:
    let current = queue.pop
    result.add(current)
    for dependent in graph.getOrDefault(current, @[]):
      inDegree[dependent] -= 1
      if inDegree[dependent] == 0:
        queue.add(dependent)

  if result.len != modules.len:
    var missing: seq[string]
    for name in modules.keys:
      if name notin result:
        missing.add(name)
    quit "Error: Circular dependency detected involving: " & missing.join(", ")

let PLACEHOLDERS = getPlaceholderMap()

proc substitutePlaceholders(code: string, shaderName: string): string =
  result = code

  # Shader-specific workgroup size
  let workgroupKey = "WORKGROUP_SIZE_" & shaderName.toUpperAscii.replace("-", "_")
  if workgroupKey in PLACEHOLDERS:
    result = result.replace("{{WORKGROUP_SIZE}}", PLACEHOLDERS[workgroupKey])

  for key, value in PLACEHOLDERS:
    result = result.replace("{{" & key & "}}", value)

  if "{{" in result:
    let startIdx = result.find("{{")
    let endIdx = result.find("}}", startIdx)
    if endIdx > startIdx:
      let placeholder = result[startIdx..endIdx+1]
      quit "Error: Unreplaced placeholder in " & shaderName & ": " & placeholder

proc bundle(srcPath: string): string =
  ## Bundle a shader with all its dependencies.
  let content = readFile(srcPath)
  let imports = parseImports(content)
  let shaderName = srcPath.extractFilename.replace(".wgsl", "")

  if imports.len == 0:
    return substitutePlaceholders(content, shaderName)

  var loaded: Table[string, Module]
  var toProcess = imports
  while toProcess.len > 0:
    let name = toProcess.pop
    if name notin loaded:
      let m = loadModule(name, loaded)
      for dep in m.imports:
        if dep notin loaded:
          toProcess.add(dep)

  let order = topologicalSort(loaded)

  var output = "// =============================================================================\n"
  output &= "// AUTO-GENERATED BY tools/wgsl_bundle.nim - DO NOT EDIT DIRECTLY\n"
  output &= "// =============================================================================\n"
  output &= "// Source: " & srcPath & "\n"
  output &= "// Bundled modules: " & order.join(", ") & "\n"
  output &= "// Generated: " & $now() & "\n"
  output &= "// =============================================================================\n\n"

  for name in order:
    let m = loaded[name]
    output &= "// ─────────────────────────────────────────────────────────────────────────────\n"
    output &= "// MODULE: " & name & "\n"
    output &= "// Source: " & m.path & "\n"
    output &= "// ─────────────────────────────────────────────────────────────────────────────\n\n"
    output &= stripImportDirectives(m.content).strip & "\n\n"

  output &= "// ─────────────────────────────────────────────────────────────────────────────\n"
  output &= "// MAIN SHADER\n"
  output &= "// ─────────────────────────────────────────────────────────────────────────────\n\n"
  output &= stripImportDirectives(content)

  result = substitutePlaceholders(output, shaderName)

  # Reject WGSL the browser will refuse to parse. The bundle is the last point
  # where anything Nim-side sees this text; past here it is a string embedded in
  # app.js and the only reader is the GPU, whose complaint arrives as a black
  # window rather than as a build failure. See src/wgsl_lint.nim.
  let offenders = namedFieldConstructorLines(result)
  if offenders.len > 0:
    let bundledLines = result.splitLines
    var report = "Error: named-field struct constructor in " & shaderName &
      " — WGSL constructors are positional only.\n"
    for lineNumber in offenders:
      report &= "  bundled line " & $lineNumber & ": " &
        bundledLines[lineNumber - 1].strip & "\n"
    quit report

  # Reject a shader whose declared bindings disagree with the manifest.
  # render.wgsl and glow.wgsl share one hand-built bind-group layout with no
  # compile-time check of its own; this is the check — see
  # ExpectedShaderBindings in src/wgsl_lint.nim. A shader absent from that
  # table fails the same way an unregistered pass fails
  # webgpu_compute.getExpectedEntryCount: silence is not a pass.
  if shaderName notin ExpectedShaderBindings:
    quit "Error: " & shaderName & " has no entry in ExpectedShaderBindings " &
      "(src/wgsl_lint.nim). Register its declared bindings before it can bundle."
  let declaredBindings = bindingsDeclared(result)
  let expectedBindings = ExpectedShaderBindings[shaderName]
  if declaredBindings != expectedBindings:
    quit "Error: binding mismatch in " & shaderName & "\n" &
      "  expected: " & $expectedBindings & "\n" &
      "  got:      " & $declaredBindings

const PlaceholderSources = [
  "src/shader_config.nim",
  "src/field_core.nim",
  "src/bloom_core.nim",
  "src/colormap_core.nim",
  "src/camera_core.nim",
  "src/memory_layout.nim",
]
  ## The Nim modules whose constants feed {{PLACEHOLDER}} substitution
  ## (shader_config.getPlaceholderMap and the pure modules it draws from).
  ## An edit to any of them changes bundled output without touching a .wgsl
  ## file, so needsRebuild must treat them as inputs — otherwise a tuning
  ## edit ships silently stale shaders.

proc needsRebuild(srcPath, outPath: string): bool =
  if not fileExists(outPath):
    return true

  let outMtime = getLastModificationTime(outPath)

  if getLastModificationTime(srcPath) > outMtime:
    return true

  let content = readFile(srcPath)
  for name in parseImports(content):
    let modPath = ModulesDir / name & ".wgsl"
    if fileExists(modPath) and getLastModificationTime(modPath) > outMtime:
      return true

  for placeholderSource in PlaceholderSources:
    if fileExists(placeholderSource) and
        getLastModificationTime(placeholderSource) > outMtime:
      return true

  return false

# WGSL struct modules generated from the Nim layout tables in gpu_types.nim, the
# single source of truth. Emitted into ModulesDir before import resolution so a
# shader can `//! import` them. Kept out of version control (see .gitignore);
# the bundler recreates them every build.

proc generateStructModule(name: string, header, body: string) =
  ## Write ModulesDir/<name>.wgsl only when its content changes, so mtime-based
  ## incremental rebuilds still fire exactly when the layout actually changed.
  let path = ModulesDir / name & ".wgsl"
  let content = header & body
  if not fileExists(path) or readFile(path) != content:
    writeFile(path, content)
    echo "  Generated module: ", name, ".wgsl"

proc structModuleHeader(moduleName, layoutName: string, notes: string = ""): string =
  ## `notes` carries the layout's GpuStruct.notes verbatim (already "// "-prefixed
  ## WGSL comment lines) between the banner and the struct body.
  result = "// =============================================================================\n" &
    "// MODULE: " & moduleName & "\n" &
    "// AUTO-GENERATED from src/gpu_types.nim (" & layoutName & ") - DO NOT EDIT\n" &
    "// Regenerated by tools/wgsl_bundle.nim on every build.\n" &
    "// =============================================================================\n\n"
  if notes.len > 0:
    result &= notes & "\n"

proc generateStructModules() =
  generateStructModule("particle",
    structModuleHeader("particle", "ParticleLayout", ParticleLayout.notes),
    toWgslStruct(ParticleLayout) & "\n" &
      "const MAX_SPECIES: u32 = " & $memory_layout.MAX_SPECIES & "u;\n")
  generateStructModule("grid_params",
    structModuleHeader("grid_params", "GridParamsLayout", GridParamsLayout.notes),
    toWgslStruct(GridParamsLayout))
  generateStructModule("scan_params",
    structModuleHeader("scan_params", "ScanParamsLayout", ScanParamsLayout.notes),
    toWgslStruct(ScanParamsLayout))
  generateStructModule("sim_params",
    structModuleHeader("sim_params", "SimParamsLayout"),
    toWgslStruct(SimParamsLayout))
  generateStructModule("render_params",
    structModuleHeader("render_params", "RenderParamsLayout"),
    toWgslStruct(RenderParamsLayout))
  generateStructModule("fade_params",
    structModuleHeader("fade_params", "FadeParamsLayout"),
    toWgslStruct(FadeParamsLayout))
  generateStructModule("camera",
    structModuleHeader("camera", "CameraLayout"),
    toWgslStruct(CameraLayout))
  generateStructModule("field_params",
    structModuleHeader("field_params", "FieldParamsLayout"),
    toWgslStruct(FieldParamsLayout))
  generateStructModule("reaction_params",
    structModuleHeader("reaction_params", "ReactionParamsLayout"),
    toWgslStruct(ReactionParamsLayout))
  generateStructModule("species_chemistry",
    structModuleHeader("species_chemistry", "SpeciesChemistryLayout"),
    toWgslStruct(SpeciesChemistryLayout))
  generateStructModule("bloom_params",
    structModuleHeader("bloom_params", "BloomParamsLayout"),
    toWgslStruct(BloomParamsLayout))
  generateStructModule("tonemap_params",
    structModuleHeader("tonemap_params", "TonemapParamsLayout"),
    toWgslStruct(TonemapParamsLayout))
  generateStructModule("overlay_params",
    structModuleHeader("overlay_params", "OverlayParamsLayout"),
    toWgslStruct(OverlayParamsLayout))

proc main() =
  echo "WGSL Shader Bundler"
  echo "==================="

  if not dirExists(SrcDir):
    echo "Note: Source directory ", SrcDir, " does not exist yet."
    echo "Creating passthrough for existing shaders..."

    # No src/ directory yet: report it and exit without bundling.
    echo "No source shaders found. Run 'nimble all' after migrating shaders to src/."
    return

  # Generate struct modules from gpu_types.nim before resolving imports.
  generateStructModules()

  var bundled = 0
  var skipped = 0

  for srcFile in walkFiles(SrcDir / "*.wgsl"):
    let name = srcFile.extractFilename
    let outPath = OutDir / name

    if needsRebuild(srcFile, outPath):
      echo "  Bundling: ", name
      let output = bundle(srcFile)
      writeFile(outPath, output)
      bundled += 1
    else:
      skipped += 1

  echo ""
  echo "Summary: ", bundled, " bundled, ", skipped, " unchanged"

when isMainModule:
  main()
