/* Generated by the Nim Compiler v2.2.6 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var objectID_771752114 = [0];

function asFloat__worker_u96(bits_p0) {
  var result_570425442 = 0.0;

  BeforeRet: {
    var arr_570425443 = new Float32Array(1);
    var iarr_570425444 = new Int32Array(arr_570425443["buffer"]);
    iarr_570425444[0] = bits_p0;
    result_570425442 = arr_570425443[0];
    break BeforeRet;
  };

  return result_570425442;

}

function HEX2BHEX3D__worker_u213(x_p0, x_p0_Idx, y_p1) {
    x_p0[x_p0_Idx] = (x_p0[x_p0_Idx] + y_p1);

  
}

function HEX2DHEX3D__worker_u223(x_p0, x_p0_Idx, y_p1) {
    x_p0[x_p0_Idx] = (x_p0[x_p0_Idx] - y_p1);

  
}

function computeForces__worker_u135(startIdx_p0, endIdx_p1, px_p2, py_p3, species_p4, W_p5, H_p6, rMax_p7, gridW_p8, gridH_p9, cellSize_p10, fMul_p11, dt_p12, mouseX_p13, mouseY_p14, mouseDown_p15) {
                                      var Temporary13;

    var rMaxSq_570425496 = (rMax_p7 * rMax_p7);
    var invR_570425497 = (1.0 / rMax_p7);
    var halfW_570425498 = (W_p5 * 0.5);
    var halfH_570425499 = (H_p6 * 0.5);
    var invCellSize_570425500 = (1.0 / cellSize_p10);
    var md2Limit_570425501 = 90000.0;
    Label1: {
      var i_570425502 = 0;
      var res_570425741 = startIdx_p0;
      Label2: {
          Label3: while (true) {
          if (!(res_570425741 < endIdx_p1)) break Label3;
            i_570425502 = res_570425741;
            var xi_570425503 = px_p2[((i_570425502) | 0)];
            var yi_570425504 = py_p3[((i_570425502) | 0)];
            var si_570425505 = species_p4[((i_570425502) | 0)];
            var rowOffset_570425506 = (((si_570425505) | 0) * 6);
            var fx_570425507 = [0.0];
            var fy_570425508 = [0.0];
            var cx_570425509 = ((xi_570425503 * invCellSize_570425500) | 0);
            var cy_570425510 = ((yi_570425504 * invCellSize_570425500) | 0);
            Label4: {
              var dy_570425515 = 0;
              var res_570425739 = (-1);
              Label5: {
                  Label6: while (true) {
                  if (!(res_570425739 <= 1)) break Label6;
                    dy_570425515 = res_570425739;
                    var ny_570425516 = (cy_570425510 + ((dy_570425515) | 0));
                    var wrapY_570425517 = 0.0;
                    if ((ny_570425516 < 0)) {
                    ny_570425516 += gridH_p9;
                    wrapY_570425517 = -(H_p6);
                    }
                    else {
                    if ((gridH_p9 <= ny_570425516)) {
                    ny_570425516 -= gridH_p9;
                    wrapY_570425517 = H_p6;
                    }
                    }
                    var nyIdx_570425526 = (ny_570425516 * gridW_p8);
                    Label7: {
                      var dx_570425531 = 0;
                      var res_570425737 = (-1);
                      Label8: {
                          Label9: while (true) {
                          if (!(res_570425737 <= 1)) break Label9;
                            dx_570425531 = res_570425737;
                            var nx_570425532 = (cx_570425509 + ((dx_570425531) | 0));
                            var wrapX_570425533 = 0.0;
                            if ((nx_570425532 < 0)) {
                            nx_570425532 += gridW_p8;
                            wrapX_570425533 = -(W_p5);
                            }
                            else {
                            if ((gridW_p8 <= nx_570425532)) {
                            nx_570425532 -= gridW_p8;
                            wrapX_570425533 = W_p5;
                            }
                            }
                            var cell_570425542 = (nyIdx_570425526 + nx_570425532);
                            var start_570425543 = gridOffsets_570425399[0][((cell_570425542) | 0)];
                            var count_570425544 = ((gridCounts_570425398[0][((cell_570425542) | 0)]) | 0);
                            var fin_570425545 = (start_570425543 + count_570425544);
                            Label10: {
                              var j_570425546 = 0;
                              var res_570425734 = start_570425543;
                              Label11: {
                                  Label12: while (true) {
                                  if (!(res_570425734 < fin_570425545)) break Label12;
                                    j_570425546 = res_570425734;
                                    var ddx_570425547 = ((px_p2[((j_570425546) | 0)] + wrapX_570425533) - xi_570425503);
                                    var ddy_570425548 = ((py_p3[((j_570425546) | 0)] + wrapY_570425517) - yi_570425504);
                                    var d2_570425549 = ((ddx_570425547 * ddx_570425547) + (ddy_570425548 * ddy_570425548));
                                    if (((0.0 < d2_570425549) && (d2_570425549 < rMaxSq_570425496))) {
                                    var d_570425550 = Math.sqrt(d2_570425549);
                                    var r_570425551 = (d_570425550 * invR_570425497);
                                    var s_j_570425552 = species_p4[((j_570425546) | 0)];
                                    var attr_570425553 = matrix_570425401[0][(((rowOffset_570425506 + ((s_j_570425552) | 0))) | 0)];
                                    var f_570425554 = 0.0;
                                    if ((r_570425551 < 0.3)) {
                                    f_570425554 = ((r_570425551 / 0.3) - 1.0);
                                    }
                                    else {
                                      var t_570425555 = ((2.0 * r_570425551) - 1.3);
                                      if ((t_570425555 < 0.0)) {
                                      Temporary13 = -(t_570425555);
                                      }
                                      else {
                                      Temporary13 = t_570425555;
                                      }
                                      
                                      var abs_t_570425556 = Temporary13;
                                      f_570425554 = (attr_570425553 * (1.0 - (abs_t_570425556 / 0.7)));
                                    }
                                    
                                    f_570425554 = ((f_570425554 * fMul_p11) / d_570425550);
                                    HEX2BHEX3D__worker_u213(fx_570425507, 0, (ddx_570425547 * f_570425554));
                                    HEX2BHEX3D__worker_u213(fy_570425508, 0, (ddy_570425548 * f_570425554));
                                    }
                                    
                                    res_570425734 += 1;
                                  }
                              };
                            };
                            res_570425737 += 1;
                          }
                      };
                    };
                    res_570425739 += 1;
                  }
              };
            };
            if (mouseDown_p15) {
            var mdx_570425565 = [(mouseX_p13 - xi_570425503)];
            var mdy_570425566 = [(mouseY_p14 - yi_570425504)];
            if ((halfW_570425498 < mdx_570425565[0])) {
            HEX2DHEX3D__worker_u223(mdx_570425565, 0, W_p5);
            }
            else {
            if ((mdx_570425565[0] < -(halfW_570425498))) {
            HEX2BHEX3D__worker_u213(mdx_570425565, 0, W_p5);
            }
            }
            if ((halfH_570425499 < mdy_570425566[0])) {
            HEX2DHEX3D__worker_u223(mdy_570425566, 0, H_p6);
            }
            else {
            if ((mdy_570425566[0] < -(halfH_570425499))) {
            HEX2BHEX3D__worker_u213(mdy_570425566, 0, H_p6);
            }
            }
            var md2_570425583 = ((mdx_570425565[0] * mdx_570425565[0]) + (mdy_570425566[0] * mdy_570425566[0]));
            if (((0.0 < md2_570425583) && (md2_570425583 < md2Limit_570425501))) {
            var md_570425584 = Math.sqrt(md2_570425583);
            var mf_570425585 = ((0.5 * (1.0 - (md_570425584 / 300.0))) / md_570425584);
            HEX2BHEX3D__worker_u213(fx_570425507, 0, (mdx_570425565[0] * mf_570425585));
            HEX2BHEX3D__worker_u213(fy_570425508, 0, (mdy_570425566[0] * mf_570425585));
            }
            
            }
            
            vxDelta_570425396[0][((i_570425502) | 0)] = (fx_570425507[0] * dt_p12);
            vyDelta_570425397[0][((i_570425502) | 0)] = (fy_570425508[0] * dt_p12);
            res_570425741 += 1;
          }
      };
    };

  
}

function workLoop__worker_u250() {
          var Temporary3;
          var Temporary4;
          var Temporary5;

    var lastFrame_570425595 = 0;
    Label1: {
        Label2: while (true) {
        if (!true) break Label2;
          Atomics.wait(syncBuffer_570425400[0], 0, lastFrame_570425595);
          lastFrame_570425595 = Atomics.load(syncBuffer_570425400[0], 0);
          var workerCount_570425596 = syncBuffer_570425400[0][1];
          var baseIdx_570425597 = (2 + (myIndex_570425402[0] * 2));
          startIdx_570425403[0] = syncBuffer_570425400[0][((baseIdx_570425597) | 0)];
          endIdx_570425404[0] = syncBuffer_570425400[0][(((baseIdx_570425597 + 1)) | 0)];
          var configOffset_570425598 = (2 + (workerCount_570425596 * 2));
          var W_570425599 = asFloat__worker_u96(syncBuffer_570425400[0][(((configOffset_570425598 + 0)) | 0)]);
          var H_570425600 = asFloat__worker_u96(syncBuffer_570425400[0][(((configOffset_570425598 + 1)) | 0)]);
          var rMax_570425601 = asFloat__worker_u96(syncBuffer_570425400[0][(((configOffset_570425598 + 2)) | 0)]);
          var gridW_570425602 = syncBuffer_570425400[0][(((configOffset_570425598 + 3)) | 0)];
          var gridH_570425603 = syncBuffer_570425400[0][(((configOffset_570425598 + 4)) | 0)];
          var cellSize_570425604 = asFloat__worker_u96(syncBuffer_570425400[0][(((configOffset_570425598 + 5)) | 0)]);
          var fMul_570425605 = asFloat__worker_u96(syncBuffer_570425400[0][(((configOffset_570425598 + 6)) | 0)]);
          var dt_570425606 = asFloat__worker_u96(syncBuffer_570425400[0][(((configOffset_570425598 + 7)) | 0)]);
          var mouseX_570425607 = asFloat__worker_u96(syncBuffer_570425400[0][(((configOffset_570425598 + 8)) | 0)]);
          var mouseY_570425608 = asFloat__worker_u96(syncBuffer_570425400[0][(((configOffset_570425598 + 9)) | 0)]);
          var mouseDown_570425609 = !((syncBuffer_570425400[0][(((configOffset_570425598 + 10)) | 0)] == 0));
          var bufferParity_570425610 = syncBuffer_570425400[0][(((configOffset_570425598 + 11)) | 0)];
          if ((bufferParity_570425610 == 0)) {
          Temporary3 = pxA_570425390[0];
          }
          else {
          Temporary3 = pxB_570425392[0];
          }
          
          var px_570425611 = Temporary3;
          if ((bufferParity_570425610 == 0)) {
          Temporary4 = pyA_570425391[0];
          }
          else {
          Temporary4 = pyB_570425393[0];
          }
          
          var py_570425612 = Temporary4;
          if ((bufferParity_570425610 == 0)) {
          Temporary5 = sA_570425394[0];
          }
          else {
          Temporary5 = sB_570425395[0];
          }
          
          var species_570425613 = Temporary5;
          computeForces__worker_u135(startIdx_570425403[0], endIdx_570425404[0], px_570425611, py_570425612, species_570425613, W_570425599, H_570425600, rMax_570425601, gridW_570425602, gridH_570425603, cellSize_570425604, fMul_570425605, dt_570425606, mouseX_570425607, mouseY_570425608, mouseDown_570425609);
          var doneOffset_570425614 = ((configOffset_570425598 + 16) + myIndex_570425402[0]);
          Atomics.store(syncBuffer_570425400[0], ((doneOffset_570425614) | 0), 1);
          Atomics.notify(syncBuffer_570425400[0], ((doneOffset_570425614) | 0));
        }
    };

  
}

function onMessage__worker_u287(e_p0) {
    var msg_570425633 = e_p0.data;
    var mType_570425638 = (msg_570425633["type"]);
    if ((mType_570425638 == "init")) {
    myIndex_570425402[0] = (msg_570425633.workerIndex);
    pxA_570425390[0] = new Float32Array(msg_570425633.pxBufferA);
    pyA_570425391[0] = new Float32Array(msg_570425633.pyBufferA);
    sA_570425394[0] = new Uint8Array(msg_570425633.speciesBufferA);
    pxB_570425392[0] = new Float32Array(msg_570425633.pxBufferB);
    pyB_570425393[0] = new Float32Array(msg_570425633.pyBufferB);
    sB_570425395[0] = new Uint8Array(msg_570425633.speciesBufferB);
    vxDelta_570425396[0] = new Float32Array(msg_570425633.vxDeltaBuffer);
    vyDelta_570425397[0] = new Float32Array(msg_570425633.vyDeltaBuffer);
    gridCounts_570425398[0] = new Uint16Array(msg_570425633.gridCountsBuffer);
    gridOffsets_570425399[0] = new Uint32Array(msg_570425633.gridOffsetsBuffer);
    syncBuffer_570425400[0] = new Int32Array(msg_570425633.syncBuffer);
    matrix_570425401[0] = new Float32Array(msg_570425633.matrixBuffer);
    workLoop__worker_u250();
    }
    

  
}
var pxA_570425390 = [null];
var pyA_570425391 = [null];
var pxB_570425392 = [null];
var pyB_570425393 = [null];
var sA_570425394 = [null];
var sB_570425395 = [null];
var vxDelta_570425396 = [null];
var vyDelta_570425397 = [null];
var gridCounts_570425398 = [null];
var gridOffsets_570425399 = [null];
var syncBuffer_570425400 = [null];
var matrix_570425401 = [null];
var myIndex_570425402 = [0];
var startIdx_570425403 = [0];
var endIdx_570425404 = [0];
self["onmessage"] = onMessage__worker_u287;
