/* Generated by the Nim Compiler v2.2.6 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var objectID_771752114 = [0];

function asFloat__worker_u51(bits_p0) {
  var result_570425397 = 0.0;

      floatConvArr_570425393[0][0] = 0;
  intConvArr_570425394[0][0] = bits_p0;
  return floatConvArr_570425393[0][0];
  

  return result_570425397;

}

function workLoop__worker_u54() {
    var lastFrame_570425399 = 0;
    Label1: {
        Label2: while (true) {
        if (!true) break Label2;
          Atomics.wait(syncBuffer_570425391[0], 0, lastFrame_570425399);
          lastFrame_570425399 = Atomics.load(syncBuffer_570425391[0], 0);
          var workerCount_570425400 = syncBuffer_570425391[0][1];
          var baseIdx_570425401 = (2 + (myIndex_570425388[0] * 2));
          var startIdx_570425402 = syncBuffer_570425391[0][((baseIdx_570425401) | 0)];
          var endIdx_570425403 = syncBuffer_570425391[0][(((baseIdx_570425401 + 1)) | 0)];
          var configOffset_570425404 = (2 + (workerCount_570425400 * 2));
          var W_570425405 = asFloat__worker_u51(syncBuffer_570425391[0][(((configOffset_570425404 + 0)) | 0)]);
          var H_570425406 = asFloat__worker_u51(syncBuffer_570425391[0][(((configOffset_570425404 + 1)) | 0)]);
          var rMax_570425407 = asFloat__worker_u51(syncBuffer_570425391[0][(((configOffset_570425404 + 2)) | 0)]);
          var gridW_570425408 = syncBuffer_570425391[0][(((configOffset_570425404 + 3)) | 0)];
          var gridH_570425409 = syncBuffer_570425391[0][(((configOffset_570425404 + 4)) | 0)];
          var fMul_570425410 = asFloat__worker_u51(syncBuffer_570425391[0][(((configOffset_570425404 + 6)) | 0)]);
          var dt_570425411 = asFloat__worker_u51(syncBuffer_570425391[0][(((configOffset_570425404 + 7)) | 0)]);
          var mouseX_570425412 = asFloat__worker_u51(syncBuffer_570425391[0][(((configOffset_570425404 + 8)) | 0)]);
          var mouseY_570425413 = asFloat__worker_u51(syncBuffer_570425391[0][(((configOffset_570425404 + 9)) | 0)]);
          var mouseDown_570425414 = !((syncBuffer_570425391[0][(((configOffset_570425404 + 10)) | 0)] == 0));
          var bufferParity_570425415 = syncBuffer_570425391[0][(((configOffset_570425404 + 11)) | 0)];
          var particleCount_570425416 = syncBuffer_570425391[0][(((configOffset_570425404 + 12)) | 0)];
              physicsStepRangeFn_570425390[0](
      startIdx_570425402, endIdx_570425403, particleCount_570425416,
      bufferParity_570425415,
      dt_570425411, W_570425405, H_570425406, rMax_570425407, fMul_570425410,
      gridW_570425408, gridH_570425409,
      mouseX_570425412, mouseY_570425413, mouseDown_570425414 ? 1.0 : 0.0
    );
    
          var doneOffset_570425417 = ((configOffset_570425404 + 16) + myIndex_570425388[0]);
          Atomics.store(syncBuffer_570425391[0], ((doneOffset_570425417) | 0), 1);
          Atomics.notify(syncBuffer_570425391[0], ((doneOffset_570425417) | 0));
        }
    };

  
}

function initWasmAndStart__worker_u74(module_p0) {
    wasmModule_570425389[0] = module_p0;
      var cwrapArgs = ['number','number','number','number',
                   'number','number','number','number','number',
                   'number','number','number','number','number'];
  physicsStepRangeFn_570425390[0] = wasmModule_570425389[0].cwrap('physicsStepRange', null, cwrapArgs);
  console.log('WASM Worker ' + myIndex_570425388[0] + ' initialized (zero-copy mode)');
  
    workLoop__worker_u54();

  
}

function onMessage__worker_u76(e_p0) {
    var msg_570425422 = e_p0.data;
    var mType_570425427 = (msg_570425422["type"]);
    if ((mType_570425427 == "init")) {
    myIndex_570425388[0] = (msg_570425422.workerIndex);
    syncOffset_570425392[0] = (msg_570425422.syncOffset);
    floatConvArr_570425393[0] = new Float32Array(1);
    intConvArr_570425394[0] = new Int32Array(floatConvArr_570425393[0].buffer);
    var wasmMemory_570425454 = msg_570425422.wasmMemory;
    var buffer_570425455 = wasmMemory_570425454["buffer"];
    syncBuffer_570425391[0] = new Int32Array(buffer_570425455, syncOffset_570425392[0], 256);
    importScripts("/physics.js");
        createPhysicsModule({ wasmMemory: wasmMemory_570425454 }).then(initWasmAndStart__worker_u74);
    
    }
    

  
}
var myIndex_570425388 = [0];
var wasmModule_570425389 = [null];
var physicsStepRangeFn_570425390 = [null];
var syncBuffer_570425391 = [null];
var syncOffset_570425392 = [0];
var floatConvArr_570425393 = [null];
var intConvArr_570425394 = [null];
self["onmessage"] = onMessage__worker_u76;
